### ISSUE TITLE
airootfs doesn't exist

### ISSUE THREAD

**Issue by arch-user-france1** [FT-Labs/phyOS-iso#1]
![image](https://user-images.githubusercontent.com/72965843/180462161-54c853f7-0955-46fe-b133-f495eb750c89.png)
It says that /run/..../airootfs.sfs doesn't exists.

I used the ram installation method (in GRUB) and virtualbox.

**Comment by r0-zero** [comment]
Ram installation can cause issues with calamares. Can you try the top one?

**Comment by arch-user-france1** [comment]
> Ram installation can cause issues with calamares. Can you try the top one?

Seems to work. Why is there a `copy to ram` option if it doesn't work?
