### ISSUE TITLE
Windows become VERY buggy in a vm (Virtual Box), basically unusable

### ISSUE THREAD

**Issue by Zoom123498** [FT-Labs/phyOS-iso#10]
The windows try to get into place but then it starts jumping everywhere like crazy. The only thing that would fix it is going into fullscreen mode. This is before you have installed phyos, and when you install its EVEN MORE BUGGY. Windows jump everywhere, when I press right click the menu pops up and starts going everywhere. This is probably more of a issue with my vm or the settings I put in I'm not really sure. I will try and boot it on a laptop I don't use anymore, if the same issue happens I'll update you. I have a Nvidia GPU so I downloaded 1.0.2 - beta iso. I will try another vm soon, since I don't have good internet right now. I would add a video but its too large.
o/

**Comment by r0-zero** [comment]
This is not meant for a VM. Animations are really buggy in virtual machines.

**Comment by arch-user-france1** [comment]
Use virt-manager or gnome boxes, needs some additional setup (virt-manager) but is much faster.
It is not a PhyOS problem that your VM doesn't work I think and I also think @FT-Labs didn't read your message correctly.
