### ISSUE TITLE
Black screen hang after hard reset.

### ISSUE THREAD

**Issue by devinhadley** [FT-Labs/phyOS-iso#12]
After holding down the power button to power off everytime I boot back into phyos I hang at a black screen.

Lenovo X1  Yoga
Intiel I7-1260p

**Comment by r0-zero** [comment]
Other than that, does it working correctly. Also do you have windows dual boot?

**Comment by devinhadley** [comment]
> Other than that, does it working correctly. Also do you have windows dual boot?

Was working fine using v 1.02

Yes I have a three boot setup  boot with windows and pop os.

**Comment by devinhadley** [comment]
Appears to have fixed itself.
