### ISSUE TITLE
CPU overheating when idle.

### ISSUE THREAD

**Issue by devinhadley** [FT-Labs/phyOS-iso#13]
Intel i7 1260-P

No software except browser and one terminal instance running.

**Comment by devinhadley** [comment]
https://ibb.co/sqhTBD1

**Comment by r0-zero** [comment]
Do you have the Latest updates and dotfiles? Can you send screenshot of htop

**Comment by devinhadley** [comment]
Upon installing drivers in https://wiki.archlinux.org/title/intel_graphics under installation the installation was broken which im trying to troubleshoot now.

**Comment by xd003** [comment]
i think you could be facing this issue due to this - https://github.com/FT-Labs/phyOS-iso/issues/17

**Comment by r0-zero** [comment]
Solved, closing issue
