### ISSUE TITLE
conda does not work (commandnotfound error)

### ISSUE THREAD

**Issue by arch-user-france1** [FT-Labs/phyOS-iso#14]
Anaconda does not work. It says "commandnotfounderror" even after running conda init zsh (and the conda command works, but the conda activate command does not work).

**Comment by r0-zero** [comment]
That is a conda related issue, I have no idea why this is here. Try to check your path or I dont know, I have never used conda before

**Comment by arch-user-france1** [comment]
I will investigate this.
It is not really a conda issue though, might it be because of your weird way of configuring zsh?
You've created a ton of of files and instead of .zshrc you use . config/zsh/.zshrc.

**Comment by arch-user-france1** [comment]
I don't like the zsh configuration anyway, I would like to remove your .config/zsh and replace the configuration with the Manjaro configuration...
Yeah, maybe I will do that.
I could open an issue on the conda's GitHub.

**Comment by r0-zero** [comment]
You could do that, but nearly most configuration files are now put in $XDG_CONFIG_HOME. Since ZSH uses a lot of stuff lilke bookmarking and aliasing, this way they are more organized.

**Comment by arch-user-france1** [comment]
Conda does change the .config/zsh/zshrc file... At least it says that it does.

**Comment by r0-zero** [comment]
Hi,

This problem has been solved. 
Move conda codes before this function in .zshcfg
```
case "$TERM" in (rxvt|rxvt-*|st|st-*|*xterm*|(dt|k|E)term)
    local term_title () { print -n "\e]0;${(j: :q)@}\a" }
    precmd () {
      local DIR="$(print -P '[%c]')"
      term_title "$DIR" "st"
    }
    preexec () {
      local DIR="$(print -P '[%c]%#')"
      local CMD="${(j:\n:)${(f)1}}"
      #term_title "$DIR" "$CMD" use this if you want directory in command, below only prints program name
	  term_title "$CMD"
    }
  ;;
esac
```
You are good to go.
