### ISSUE TITLE
[Pulsemixer]: Not closing properly

### ISSUE THREAD

**Issue by arek-e** [FT-Labs/phyOS-iso#17]
Opening pulsemixer takes about 10 to 20% of my CPU and i cant close it even trough gotop or with [Super + q]. This lead to me opening multiple instances that cant be closed, overheating my CPU.

![pic-full-220807-1338-23](https://user-images.githubusercontent.com/59033336/183289485-8ce6cd79-95dc-4285-b854-c6664452edd4.png)

**Comment by xd003** [comment]
i face this very exact issue  . All this time  i had been wondering how is it just me & not anyone else but thankfully i am not alone xd . This pulsemixer issue pretty makes phyOS unusable for me as it overheates a lot + battery drops  quicker . My CPU usage becomes like 100% constant ( probably because mine is a lower end cpu )

**Comment by r0-zero** [comment]
Can you check if any espeak package is installed? If it is remove everythin about text to speech etc.

**Comment by r0-zero** [comment]
Otherwise you can remove pulsemixer with pavucontrol.

``` 
sudo pacman  -R pulsemixer
sudo pacman -S pavucontrol
```

**Comment by arek-e** [comment]
I checked and have not installed any espeak package or anything related to text to speech.
<details>
  <summary>Installed packages</summary>
  
a52dec 0.7.4-11
acl 2.3.1-2
adobe-source-code-pro-fonts 2.038ro+1.058it+1.018var-1
adwaita-icon-theme 42.0+r1+gc144c3d75-1
alsa-card-profiles 1:0.3.56-1
alsa-firmware 1.2.4-2
alsa-lib 1.2.7.2-1
alsa-plugins 1:1.2.7.1-1
alsa-topology-conf 1.2.5.1-1
alsa-ucm-conf 1.2.7.2-1
alsa-utils 1.2.7-1
amd-ucode 20220708.be7798e-1
aom 3.4.0-1
arandr 0.1.10-7
archlinux-keyring 20220727-1
arduino 1:1.8.19-1
arduino-builder 1.6.1-2
arduino-ctags 5.8_arduino11-4
argon2 20190702-4
asusctl 4.3.4-1
at-spi2-atk 2.38.0-1
at-spi2-core 2.44.1-1
atk 2.38.0-1
atkmm 2.28.3-1
attr 2.5.1-2
audiofile 0.3.6-6
audit 3.0.8-1
autoconf 2.71-1
automake 1.16.5-1
avahi 0.8+22+gfd482a7-3
awesome-terminal-fonts 1.1.0-4
base 3-1
bash 5.1.016-1
bc 1.07.1-4
betterlockscreen 4.0.4-1
bind 9.18.5-1
binutils 2.39-2
bison 3.8.2-4
blueberry 1.4.8-1
bluez 5.64-2
bluez-libs 5.64-2
bluez-tools 0.2.0-5
bluez-utils 5.64-2
brotli 1.0.9-8
bzip2 1.0.8-4
c-ares 1.18.1-1
ca-certificates 20210603-1
ca-certificates-mozilla 3.81-1
ca-certificates-utils 20210603-1
cairo 1.17.6-2
cairomm 1.14.3-2
calcurse 4.8.0-1
cantarell-fonts 1:0.303.1-1
cdparanoia 10.2-8
chromaprint 1.5.1-3
cifs-utils 6.15-1
cointop 1.6.10-1
conky 1.12.2-2
coreutils 9.1-1
cryptsetup 2.5.0-1
cups-filters 1.28.15-1
curl 7.84.0-2
dav1d 1.0.0-1
db 5.3.28-5
dbus 1.14.0-1
dbus-python 1.2.18-3
dconf 0.40.0-1
desktop-file-utils 0.26-2
device-mapper 2.03.16-1
dex 0.9.0-1
diffutils 3.8-1
discord 0.0.18-1
dkms 3.0.6-1
dnssec-anchors 20190629-3
double-conversion 3.2.1-1
duktape 2.7.0-4
e2fsprogs 1.46.5-4
efibootmgr 18-1
efivar 38-2
egl-wayland 2:1.1.10-1
eglexternalplatform 1.1-2
enchant 2.3.3-1
exa 0.10.1-5
exo 4.16.4-1
expat 2.4.8-1
faad2 2.10.0-1
fakeroot 1.29-1
feh 3.9-1
ffmpeg 2:5.0.1-3
ffmpeg4.4 4.4.2-3
ffmpegthumbnailer 2.2.2-4
fftw 3.3.10-3
file 5.42-1
filesystem 2021.12.07-1
findutils 4.9.0-1
flac 1.3.4-3
flex 2.6.4-3
fluidsynth 2.2.8-1
fmt 8.1.1-2
fontconfig 2:2.14.0-1
foomatic-db-engine 4:20220521-1
freetype2 2.12.1-1
fribidi 1.0.12-1
fuse-common 3.11.0-1
fuse2 2.9.9-4
fzf 0.32.0-1
gawk 5.1.1-1
gc 8.2.0-3
gcc 12.1.1-4
gcc-libs 12.1.1-4
gd 2.3.3-4
gdbm 1.23-1
gdk-pixbuf2 2.42.8-1
gettext 0.21-2
ghostscript 9.56.1-1
giflib 5.2.1-2
girara 0.3.7-1
git 2.37.1-1
gitg 2:41-1
glew 2.2.0-3
glib-networking 1:2.72.2-1
glib2 2.72.3-1
glibc 2.36-1
glibmm 2.66.4-1
glow 1.4.1-3
glslang 11.10.0-1
glu 9.0.2-3
gmp 6.2.1-2
gnome-bluetooth 3.34.5-4
gnupg 2.2.36-1
gnutls 3.7.7-1
gobject-introspection-runtime 1.72.0-1
google-chrome 104.0.5112.79-1
gotop 4.1.4-1
gpgme 1.17.1-1
gpm 1.20.7.r38.ge82d1a6-4
graphene 1.10.8-1
graphite 1:1.3.14-2
graphviz 5.0.0-1
grep 3.7-1
groff 1.22.4-7
grub 2:2.06.r261.g2f4430cc0-1
gsettings-desktop-schemas 42.0-1
gsfonts 20200910-2
gsm 1.0.22-1
gspell 1.10.0-2
gst-plugins-base 1.20.3-1
gst-plugins-base-libs 1.20.3-1
gstreamer 1.20.3-1
gtk-update-icon-cache 1:4.6.6-1
gtk2 2.24.33-2
gtk3 1:3.24.34-1
gtkmm3 3.24.6-1
gtksourceview4 4.8.3-1
gts 0.7.6.121130-2
guile 2.2.7-2
gzip 1.12-1
harfbuzz 5.1.0-1
hicolor-icon-theme 0.17-2
hidapi 0.12.0-1
hplip 1:3.22.6-1
http-parser 2.9.4-1
hwdata 0.361-1
hwloc 2.8.0-1
hyperv 5.19-1
hyphen 2.8.8-4
i3lock-color 2.13.c.4-1
iana-etc 20220603-1
icu 71.1-1
ijs 0.35-4
imagemagick 7.1.0.45-1
imlib2 1.9.1-1
iproute2 5.19.0-1
iptables 1:1.8.8-2
iputils 20211215-1
iso-codes 4.11.0-1
iw 5.19-1
jack2 1.9.21-1
jansson 2.14-2
java-runtime-common 3-3
jbig2dec 0.19-1
jemalloc 1:5.3.0-1
jgmenu 4.4.0-1
jre8-openjdk 8.345.u01-1
jre8-openjdk-headless 8.345.u01-1
json-c 0.16-1
json-glib 1.6.6-2
kbd 2.5.1-1
keyutils 1.6.3-1
kmod 30-1
krb5 1.19.3-3
l-smash 2.14.5-2
lame 3.100-4
lcms2 2.13.1-1
ldb 2:2.5.2-2
ldns 1.8.1-1
less 1:590-1
lf-png 27-0
lib32-alsa-lib 1.2.7.2-1
lib32-at-spi2-atk 2.38.0-2
lib32-at-spi2-core 2.44.1-1
lib32-atk 2.38.0-1
lib32-brotli 1.0.9-4
lib32-bzip2 1.0.8-2
lib32-cairo 1.17.6-2
lib32-colord 1.4.6-1
lib32-curl 7.84.0-1
lib32-dbus 1.14.0-1
lib32-e2fsprogs 1.46.5-1
lib32-expat 2.4.8-1
lib32-flac 1.3.4-3
lib32-fontconfig 2:2.14.0-1
lib32-freetype2 2.12.1-1
lib32-fribidi 1.0.12-1
lib32-gcc-libs 12.1.1-4
lib32-gdk-pixbuf2 2.42.8-1
lib32-glib-networking 2.72.2-1
lib32-glib2 2.72.3-1
lib32-glibc 2.36-1
lib32-gmp 6.2.1-1
lib32-gnutls 3.7.6-1
lib32-gtk3 3.24.34-1
lib32-harfbuzz 5.1.0-1
lib32-icu 71.1-1
lib32-json-glib 1.6.6-2
lib32-keyutils 1.6.3-1
lib32-krb5 1.19.3-2
lib32-lcms2 2.13.1-1
lib32-libasyncns 1:0.8+r3+g68cd5af-1
lib32-libcanberra 1:0.30+r2+gc0620e4-1
lib32-libcap 2.65-1
lib32-libcups 2.4.2-1
lib32-libdatrie 0.2.13-1
lib32-libdrm 2.4.112-1
lib32-libelf 0.187-1
lib32-libepoxy 1.5.10-1
lib32-libffi 3.4.2-4
lib32-libgcrypt 1.10.1-1
lib32-libglvnd 1.4.0-2
lib32-libgpg-error 1.45-1
lib32-libice 1.0.10-1
lib32-libidn2 2.3.3-1
lib32-libjpeg-turbo 2.1.3-1
lib32-libldap 2.6.3-1
lib32-libltdl 2.4.7-2
lib32-libogg 1.3.5-1
lib32-libpciaccess 0.16-1
lib32-libpng 1.6.37-3
lib32-libproxy 0.4.18-1
lib32-libpsl 0.21.1-2
lib32-libpulse 16.1-1
lib32-librsvg 2:2.54.4-1
lib32-libsm 1.2.3-1
lib32-libsndfile 1.1.0-1
lib32-libsoup 2.74.2-1
lib32-libssh2 1.10.0-1
lib32-libtasn1 4.18.0-1
lib32-libthai 0.1.29-1
lib32-libtiff 4.4.0-3
lib32-libtirpc 1.3.2-2
lib32-libunistring 1.0-1
lib32-libunwind 1.6.2-1
lib32-libvorbis 1.3.7-1
lib32-libx11 1.8.1-1
lib32-libxau 1.0.9-2
lib32-libxcb 1.15-1
lib32-libxcomposite 0.4.5-2
lib32-libxcrypt 4.4.28-2
lib32-libxcursor 1.2.1-1
lib32-libxdamage 1.1.5-2
lib32-libxdmcp 1.1.3-1
lib32-libxext 1.3.4-2
lib32-libxfixes 6.0.0-1
lib32-libxft 2.3.4-1
lib32-libxi 1.8-1
lib32-libxinerama 1.1.4-2
lib32-libxkbcommon 1.4.1-1
lib32-libxml2 2.9.14-1
lib32-libxrandr 1.5.2-2
lib32-libxrender 0.9.10-3
lib32-libxshmfence 1.3-2
lib32-libxtst 1.2.3-3
lib32-libxxf86vm 1.1.4-3
lib32-llvm-libs 14.0.6-2
lib32-lm_sensors 1:3.6.0.r41.g31d1f125-1
lib32-mesa 22.1.4-1
lib32-mpg123 1.30.2-1
lib32-ncurses 6.3-1
lib32-nettle 3.8-1
lib32-nvidia-utils 515.65.01-1
lib32-openssl 1:1.1.1.q-1
lib32-opus 1.3.1-2
lib32-p11-kit 0.24.1-1
lib32-pam 1.5.2-1
lib32-pango 1:1.50.8-1
lib32-pcre 8.45-1
lib32-pixman 0.40.0-1
lib32-readline 8.1.002-1
lib32-rest 0.8.1-4
lib32-sqlite 3.39.0-1
lib32-systemd 251.3-1
lib32-tdb 1.4.7-1
lib32-util-linux 2.38.1-1
lib32-v4l-utils 1.22.1-1
lib32-vulkan-icd-loader 1.3.221-1
lib32-wayland 1.21.0-1
lib32-xz 5.2.5-2
lib32-zlib 1.2.12-1
lib32-zstd 1.5.2-1
libao 1.2.2-5
libarchive 3.6.1-2
libass 0.16.0-1
libassuan 2.5.5-1
libasyncns 1:0.8+r3+g68cd5af-1
libavc1394 0.5.4-4
libavif 0.10.1-2
libbluray 1.3.1-1
libbpf 0.8.1-1
libbsd 0.11.6-2
libcanberra 1:0.30+r2+gc0620e4-1
libcap 2.65-1
libcap-ng 0.8.3-1
libcddb 1.3.2-6
libcdio 2.1.0-2
libcdio-paranoia 10.2+2.0.1-2
libcloudproviders 0.3.1-2
libcolord 1.4.6-1
libconfig 1.7.3-1
libcups 1:2.4.2-3
libcurl-gnutls 7.84.0-2
libdaemon 0.14-5
libdatrie 0.2.13-1
libdazzle 3.44.0-1
libdbusmenu-glib 16.04.0-5
libdbusmenu-gtk3 16.04.0-5
libdca 0.0.7-1
libde265 1.0.8-2
libdrm 2.4.112-1
libdvbpsi 1:1.3.3-2
libdvdnav 6.1.1-1
libdvdread 6.1.3-1
libebml 1.4.2-2
libedit 20210910_3.1-1
libelf 0.187-2
libepoxy 1.5.10-1
libev 4.33-1
libevdev 1.13.0-1
libevent 2.1.12-1
libexif 0.6.24-1
libfdk-aac 2.0.2-1
libffi 3.4.2-5
libfm-extra 1.3.2-1
libfontenc 1.1.4-3
libfreeaptx 0.1.1-1
libgcrypt 1.10.1-1
libgee 0.20.5-2
libgit2 1:1.4.4-1
libgit2-glib 1.0.0.1-2
libglvnd 1.4.0-2
libgme 0.6.3-1
libgnomekbd 1:3.26.1+r5+g54da436-1
libgpg-error 1.45-2
libgtop 2.40.0+2+g31db82ef-2
libgudev 237-2
libheif 1.12.0-3
libical 3.0.14-3
libice 1.0.10-4
libid3tag 0.15.1b-11
libidn 1.41-1
libidn2 2.3.3-1
libiec61883 1.2.0-6
libimagequant 4.0.0-1
libimobiledevice 1.3.0-5
libinput 1.21.0-1
libinstpatch 1.1.6-1
libisl 0.25-1
libjpeg-turbo 2.1.3-2
libksba 1.6.0-1
libldac 2.0.2.3-1
libldap 2.6.3-1
liblouis 3.22.0-1
liblqr 0.4.2-3
libluv 1.44.2_0-1
libmad 0.15.1b-9
libmatroska 1.6.3-2
libmaxminddb 1.6.0-3
libmd 1.0.4-1
libmediainfo 22.06-1
libmfx 22.4.4-1
libmikmod 3.3.11.1-6
libmm-glib 1.18.10-2
libmms 0.6.4-3
libmnl 1.0.5-1
libmodplug 0.8.9.0-3
libmpc 1.2.1-2
libmpcdec 1:0.1+r475-3
libmpdclient 2.20-2
libmpeg2 0.5.1-7
libndp 1.8-1
libnetfilter_conntrack 1.0.9-1
libnewt 0.52.21-8
libnfnetlink 1.0.2-1
libnfs 5.0.1-2
libnftnl 1.2.2-1
libnghttp2 1.48.0-1
libnl 3.7.0-1
libnm 1.38.2-2
libnotify 0.8.1-1
libnsl 2.0.0-2
libogg 1.3.5-1
libomxil-bellagio 0.9.3-3
libopenmpt 0.6.4-1
libp11-kit 0.24.1-1
libpaper 1.1.28-2
libpcap 1.10.1-2
libpciaccess 0.16-3
libpeas 1.32.0-1
libpgm 5.3.128-2
libpipeline 1.5.6-1
libplacebo 4.208.0-1
libplist 2.2.0-5
libpng 1.6.37-3
libproxy 0.4.18-1
libpsl 0.21.1-1
libpulse 16.1-1
libraqm 0.9.0-1
libraw1394 2.1.2-3
librsvg 2:2.54.4-1
libsamplerate 0.2.2-1
libsasl 2.1.28-1
libseccomp 2.5.4-1
libsecret 0.20.5-2
libshout 1:2.4.6-1
libsidplayfp 2.3.1-1
libsigc++ 2.10.8-1
libsm 1.2.3-3
libsndfile 1.1.0-2
libsodium 1.0.18-2
libsoup 2.74.2-2
libsoup3 3.0.7-1
libsoxr 0.1.3-2
libssh 0.9.6-1
libssh2 1.10.0-1
libstemmer 2.2.0-2
libsynctex 2022.62885-1
libsysprof-capture 3.44.0-2
libtar 1.2.20-6
libtasn1 4.18.0-1
libteam 1.31-5
libtermkey 0.22-2
libthai 0.1.29-1
libtheora 1.1.1-5
libtiff 4.4.0-3
libtirpc 1.3.2-1
libtool 2.4.7-3
libunistring 1.0-1
libunwind 1.6.2-1
libupnp 1.14.13-1
liburing 2.2-1
libusb 1.0.26-1
libusbmuxd 2.0.2-1
libuv 1.44.2-1
libva 2.15.0-1
libvdpau 1.5-1
libverto 0.3.2-4
libvisual 0.4.0-8
libvorbis 1.3.7-3
libvpx 1.12.0-1
libvterm01 0.1.4-2
libwacom 2.4.0-1
libwebp 1.2.4-1
libx11 1.8.1-3
libxau 1.0.9-4
libxaw 1.0.14-1
libxcb 1.15-1
libxcomposite 0.4.5-4
libxcrypt 4.4.28-2
libxcursor 1.2.1-1
libxcvt 0.1.2-1
libxdamage 1.1.5-4
libxdg-basedir 1.2.3-1
libxdmcp 1.1.3-4
libxext 1.3.4-4
libxfce4ui 4.16.1-1
libxfce4util 4.16.0-1
libxfixes 6.0.0-1
libxfont2 2.0.5-1
libxft-bgra 2.3.4-1
libxi 1.8-1
libxinerama 1.1.4-4
libxkbcommon 1.4.1-1
libxkbcommon-x11 1.4.1-1
libxkbfile 1.1.0-3
libxklavier 5.4-3
libxml2 2.9.14-1
libxmu 1.1.3-3
libxnvctrl 515.65.01-1
libxpm 3.5.13-3
libxrandr 1.5.2-4
libxrender 0.9.10-5
libxshmfence 1.3-3
libxslt 1.1.35-1
libxss 1.2.3-4
libxt 1.2.1-1
libxtst 1.2.3-5
libxv 1.0.11-5
libxvmc 1.0.13-1
libxxf86vm 1.1.4-5
libyuv r2322+3aebf69d-1
libzen 0.4.39-1
licenses 20220125-1
light 1.2.2-3
lilv 0.24.14-2
linux 5.18.16.arch1-1
linux-api-headers 5.18.15-1
linux-firmware 20220708.be7798e-1
linux-firmware-marvell 20220708.be7798e-1
linux-firmware-qlogic 20220708.be7798e-1
linux-firmware-whence 20220708.be7798e-1
linux-headers 5.18.16.arch1-1
llvm-libs 14.0.6-3
lm_sensors 1:3.6.0.r41.g31d1f125-1
lmdb 0.9.29-1
lsb-release 2.0.r48.3cf5103-1
lua 5.4.4-1
lua52 5.2.4-5
luajit 2.1.0.beta3.r431.g5677985d-1
lv2 1.18.6-1
lz4 1:1.9.3-2
lzo 2.10-3
m4 1.4.19-1
maim 5.7.4-3
make 4.3-3
man-db 2.10.2-1
man-pages 5.13-1
md4c 0.4.8-1
mediainfo 22.06-2
menu-cache 1.1.0-3
mesa 22.1.4-1
mesa-utils 8.5.0-2
minizip 1:1.2.12-2
mkinitcpio 31-3
mkinitcpio-busybox 1.35.0-1
mkinitcpio-nfs-utils 0.3-7
mobile-broadband-provider-info 20220725-1
mpc 0.34-2
mpd 0.23.8-1
mpfr 4.1.0.p13-3
mpg123 1.30.2-1
mpv 1:0.34.1-5
msgpack-c 4.0.0-1
mtdev 1.1.6-2
mujs 1.2.0-2
nano 6.3-1
ncurses 6.3-3
neofetch 7.1.0-2
neovim 0.7.2-3
net-snmp 5.9.1-4
netpbm 10.73.37-1
nettle 3.8.1-1
networkmanager 1.38.2-2
networkmanager-openconnect 1.2.8-2
networkmanager-openvpn 1.8.18-2
networkmanager-pptp 1.2.10-2
networkmanager-vpnc 1.2.8-2
nilfs-utils 2.2.9-1
node-gyp 9.1.0-1
nodejs 18.7.0-1
nodejs-nopt 5.0.0-2
npm 8.16.0-1
npth 1.6-3
nspr 4.34-1
nss 3.81-1
nss-mdns 0.15.1-1
ntfs-3g 2022.5.17-1
nvidia-dkms 515.65.01-1
nvidia-settings 515.65.01-1
nvidia-utils 515.65.01-1
oath-toolkit 2.6.7-1
openal 1.22.2-1
openconnect 1:9.01-2
opencore-amr 0.1.6-1
openjpeg2 2.5.0-1
openmpi 4.1.4-1
openpmix 4.1.2-1
openresolv 3.12.0-1
openssh 9.0p1-1
openssl 1.1.1.q-1
openvpn 2.5.7-1
opus 1.3.1-3
orc 0.4.32-1
os-prober 1.80-1
p11-kit 0.24.1-1
pacman 6.0.1-7
pacman-mirrorlist 20220724-1
pahole 1.23-1
pam 1.5.2-1
pambase 20211210-1
pamixer 1.6-2
pango 1:1.50.8-1
pangomm 2.46.2-1
papirus-icon-theme 20220710-1
parted 3.5-1
paru 1.11.1-1
pass 1.7.4-3
patch 2.7.6-8
pavucontrol 1:5.0+r35+g964f298-1
pciutils 3.8.0-2
pcre 8.45-1
pcre2 10.40-1
pcsclite 1.9.8-1
pdfarranger 1.8.2-1
perl 5.36.0-1
perl-alien-build 2.51-1
perl-alien-libxml2 0.17-3
perl-capture-tiny 0.48-6
perl-clone 0.45-4
perl-dbi 1.643-4
perl-error 0.17029-4
perl-ffi-checklib 0.28-3
perl-file-chdir 0.1011-4
perl-file-which 1.27-2
perl-mailtools 2.21-6
perl-path-tiny 0.122-2
perl-timedate 2.33-4
perl-xml-libxml 2.0207-3
perl-xml-namespacesupport 1.12-4
perl-xml-sax 1.02-1
perl-xml-sax-base 1.09-4
phyOS-base-themes 1.1-0
phyOS-dmenu 5.0-1
phyOS-dunst 1.9.0-0
phyOS-dwm 1.2.1-03
phyOS-fonts 1.3-03
phyOS-keyring 20240603-3
phyOS-mirrorlist 24.06-0
phyOS-plymouth-cyanide-theme 1.1-0
phyOS-sddm-simplicity-theme 1.0-0
phyOS-st 0.8.5-6
phyOS-sysconf 1.6-0
phyOS-system-scripts 2.1-05
phyOS-systemd-services 1.5-04
phyOS-xmenu 1-1
picom-animations-git 1770_Next.208.g51b2135_2022.05.29-1
pinentry 1.2.0-1
pipewire 1:0.3.56-1
pipewire-alsa 1:0.3.56-1
pixman 0.40.0-2
pkcs11-helper 1.29.0-1
pkgconf 1.8.0-1
plymouth-git 22.02.122.r54.geb1b8935-1
polkit 121-1
polkit-gnome 0.105-9
poppler 22.07.0-1
poppler-glib 22.07.0-1
popt 1.18-3
portaudio 1:19.7.0-1
power-profiles-daemon 0.12-1
powerline 2.8.2-4
powerline-common 2.8.2-4
ppp 2.4.9-1
pptpclient 1.10.0-2
procps-ng 3.3.17-1
psmisc 23.5-1
pulseaudio 16.1-1
pulseaudio-bluetooth 16.1-1
pulsemixer 1.5.1-3
python 3.10.5-2
python-appdirs 1.4.4-6
python-attrs 21.4.0-1
python-cairo 1.21.0-1
python-dateutil 2.8.2-4
python-deprecation 2.1.0-6
python-distlib 0.3.5-1
python-distro 1.7.0-1
python-docopt 0.6.2-11
python-filelock 3.6.0-1
python-gobject 3.42.2-1
python-importlib-metadata 4.8.1-3
python-jaraco.context 4.1.1-2
python-jaraco.functools 3.5.1-1
python-jaraco.text 3.8.1-1
python-lxml 4.9.1-1
python-more-itertools 8.13.0-2
python-nspektr 0.4.0-1
python-ordered-set 4.0.2-6
python-packaging 21.3-1
python-pikepdf 5.3.1-1
python-pillow 9.2.0-1
python-platformdirs 2.5.2-1
python-ply 3.11-10
python-powerline 2.8.2-4
python-psutil 5.9.1-1
python-pyparsing 3.0.9-1
python-setproctitle 1.2.3-1
python-setuptools 1:61.3.1-1
python-six 1.16.0-5
python-tomli 2.0.1-1
python-trove-classifiers 2022.7.22-1
python-typing_extensions 4.2.0-1
python-urwid 2.1.2-3
python-validate-pyproject 0.9-1
python-virtualenv 20.11.0-1
python-xlib 0.31-3
python-zipp 3.8.1-1
qpdf 10.6.3-1
qt5-base 5.15.5+kde+r174-1
qt5-declarative 5.15.5+kde+r19-1
qt5-location 5.15.5+kde+r3-1
qt5-quickcontrols2 5.15.5+kde+r5-1
qt5-sensors 5.15.5+kde+r0-1
qt5-svg 5.15.5+kde+r11-1
qt5-translations 5.15.5+kde+r2-1
qt5-webchannel 5.15.5+kde+r3-1
qt5-webkit 5.212.0alpha4-15
qt5-x11extras 5.15.5+kde+r0-1
qt5-xmlpatterns 5.15.5+kde+r0-1
qt5ct 1.5-2
ranger 1.9.3-4
rav1e 0.4.1-2
re2 1:20220601-1
readline 8.1.002-1
reflector 2021.11-5
rest 0.8.1+r4+ge5ee6ef-1
ripgrep 13.0.0-2
rofi 1.7.3-1
rsync 3.2.4-2
rtkit 0.13-2
rubberband 3.0.0-2
run-parts 5.5-1
rust 1:1.62.1-1
s-tui 1.1.3-2
sbc 2.0-1
sddm 0.19.0-8
sdl2 2.0.22-2
sed 4.8-1
semver 7.3.7-1
serd 0.30.14-1
shaderc 2022.1-4
shadow 4.11.1-1
shared-mime-info 2.0+144+g13695c7-1
slang 2.3.2-2
slop 7.5-7
smbclient 4.16.4-2
snappy 1.1.9-2
sord 0.16.12-3
sound-theme-freedesktop 0.8-5
speex 1.2.1-1
speexdsp 1.2.1-1
spirv-tools 2022.1-1
spotify 1:1.1.84.716-2
sqlite 3.39.2-1
sratom 0.6.12-1
srt 1.5.0-1
startup-notification 0.12-7
stoken 0.92-4
stress 1.0.5-1
sudo 1.9.11.p3-1
svt-av1 1.1.0-1
sysfsutils 2.1.1-1
systemd 251.3-1
systemd-libs 251.3-1
systemd-sysvcompat 251.3-1
taglib 1.12-1
talloc 2.3.4-1
tar 1.34-1
tdb 1.4.7-1
tevent 1:0.13.0-1
texinfo 6.8-2
thunar 4.16.11-2
tinyxml2 9.0.0-1
tpm2-tss 3.2.0-1
tracker3 3.3.2-1
tree 2.0.2-1
tree-sitter 0.20.6-1
tslib 1.22-1
ttf-anonymous-pro 1.003-6
ttf-bitstream-vera 1.10-14
ttf-caladea 20200113-3
ttf-carlito 20130920-6
ttf-cascadia-code 2111.01-1
ttf-cormorant 3.609-1
ttf-croscore 20220607-1
ttf-dejavu 2.37+18+g9b5d1b2f-3
ttf-eurof 1.0-2
ttf-fantasque-sans-mono 1.8.0-2
ttf-fira-code 6.2-2
ttf-fira-mono 2:3.206-4
ttf-fira-sans 1:4.301-2
ttf-font-awesome 6.1.2-1
ttf-ibm-plex 6.0.2-1
ttf-inconsolata 1:3.000-3
ttf-jetbrains-mono 2.242-2
ttf-joypixels 7.0.0-1
ttf-lato 2.015-4
ttf-liberation 2.1.5-1
ttf-linux-libertine 5.3.0-8
ttf-linux-libertine-g 20120116-6
ttf-monofur 1.0-7
ttf-nerd-fonts-symbols-mono 2.1.0+36+gd0bf73a1-6
ttf-opensans 1.101-2
ttf-proggy-clean 1.1.5-2
twolame 0.4.0-2
tzdata 2022a-1
uchardet 0.0.7-1
ueberzug 18.1.9-3
unclutter 1:1.6-2
ungoogled-chromium 103.0.5060.134-1
unibilium 2.1.1-1
unzip 6.0-18
upower 0.99.20-1
usbmuxd 1.1.1-1
usbutils 014-2
util-linux 2.38.1-1
util-linux-libs 2.38.1-1
v4l-utils 1.22.1-1
vid.stab 1.1-3
virtualbox-guest-utils 6.1.36-1
vlc 3.0.17.4-7
vmaf 2.3.1-1
vpnc 1:0.5.3.r506.r204-1
vulkan-icd-loader 1.3.221-1
wavpack 5.5.0-1
wayland 1.21.0-1
wayland-protocols 1.26-1
webrtc-audio-processing 0.3.1-3
wget 1.21.3-1
which 2.21-5
wildmidi 0.4.4-1
wireless_tools 30.pre9-3
wireplumber 0.4.11-2
wkhtmltopdf 0.12.6-1
wmctrl 1.07-6
woff2 1.0.2-4
wpa_supplicant 2:2.10-5
x264 3:0.164.r3081.19856cc-2
x265 3.5-3
xapp 2.2.14-1
xcape 1.2-4
xcb-proto 1.15.2-1
xcb-util 0.4.0-4
xcb-util-cursor 0.1.3-4
xcb-util-image 0.4.0-4
xcb-util-keysyms 0.4.0-4
xcb-util-renderutil 0.3.9-4
xcb-util-wm 0.4.1-4
xcb-util-xrm 1.3-2
xclip 0.13-3
xdg-user-dirs 0.17-3
xdg-utils 1.1.3+21+g1a58bc2-1
xdotool 3.20211022.1-1
xf86-input-elographics 1.4.2-3
xf86-input-evdev 2.10.6-3
xf86-input-libinput 1.2.1-1
xf86-input-vmmouse 13.1.0-6
xf86-input-void 1.4.1-6
xf86-video-amdgpu 22.0.0-1
xf86-video-ati 1:19.1.0.r9.g5eba006e-2
xf86-video-fbdev 0.5.0-3
xf86-video-intel 1:2.99.917+916+g31486f40-2
xf86-video-nouveau 1.0.17-2
xf86-video-openchrome 0.6.0.r754.g15c868a-1
xf86-video-vesa 2.5.0-3
xf86-video-vmware 13.3.0-3
xfconf 4.16.0-2
xkeyboard-config 2.36-2
xmlsec 1.2.34-1
xorg-bdftopcf 1.1-3
xorg-docs 1.7.2-1
xorg-font-util 1.3.3-1
xorg-fonts-100dpi 1.0.3-7
xorg-fonts-75dpi 1.0.3-7
xorg-fonts-alias-100dpi 1.0.4-1
xorg-fonts-alias-75dpi 1.0.4-1
xorg-fonts-encodings 1.0.6-1
xorg-iceauth 1.0.9-1
xorg-mkfontscale 1.2.2-1
xorg-server 21.1.4-1
xorg-server-common 21.1.4-1
xorg-server-devel 21.1.4-1
xorg-server-xephyr 21.1.4-1
xorg-server-xnest 21.1.4-1
xorg-server-xvfb 21.1.4-1
xorg-sessreg 1.1.2-3
xorg-setxkbmap 1.3.3-1
xorg-smproxy 1.0.6-4
xorg-util-macros 1.19.3-1
xorg-x11perf 1.6.1-3
xorg-xauth 1.1.2-1
xorg-xbacklight 1.2.3-3
xorg-xcmsdb 1.0.6-1
xorg-xcursorgen 1.0.7-3
xorg-xdpyinfo 1.3.3-4
xorg-xdriinfo 1.0.6-3
xorg-xev 1.2.5-1
xorg-xfontsel 1.1.0-1
xorg-xgamma 1.0.6-4
xorg-xhost 1.0.8-3
xorg-xinit 1.4.1-3
xorg-xinput 1.6.3-3
xorg-xkbcomp 1.4.5-1
xorg-xkbevd 1.1.4-4
xorg-xkbutils 1.0.5-1
xorg-xkill 1.0.5-3
xorg-xlsatoms 1.1.3-3
xorg-xlsclients 1.1.4-3
xorg-xmessage 1.0.6-1
xorg-xmodmap 1.0.11-1
xorg-xpr 1.1.0-1
xorg-xprop 1.2.5-1
xorg-xrandr 1.5.1-2
xorg-xrdb 1.2.1-1
xorg-xrefresh 1.0.7-1
xorg-xset 1.2.4-3
xorg-xsetroot 1.1.2-3
xorg-xvinfo 1.1.4-3
xorg-xwayland 22.1.3-1
xorg-xwd 1.0.8-1
xorg-xwininfo 1.1.5-3
xorg-xwud 1.0.6-1
xorgproto 2022.1-1
xsel 1.2.0.20200527-1
xvidcore 1.3.7-2
xwallpaper 0.7.4-1
xxhash 0.8.1-2
xz 5.2.5-3
yajl 2.1.0-5
zathura 0.4.9-1
zathura-pdf-poppler 0.3.0-1
zeromq 4.3.4-2
zimg 3.0.4-1
zip 3.0-10
zlib 1:1.2.12-2
zsh 5.9-1
zsh-completions 0.34.0-1
zsh-fast-syntax-highlighting-git r905.721be2a-1
zstd 1.5.2-7
zziplib 0.13.72-1


</details>

**Comment by arek-e** [comment]
Accidently closed

**Comment by r0-zero** [comment]
I have no idea why this is happening. Just remove than use pavucontrol if you have issues for now, I will check this. Also as a side note, I have opened 20 pulsemixer instances and could close all of them. There is something buggy here

**Comment by r0-zero** [comment]
Also can I learn which iso version you are using? Is it the latest one ?

**Comment by r0-zero** [comment]
When I opened multiple pulsemixer instances, I have received the same bug too. Pulsemixer is going to get replaced with pavucontrol, I will ping here again. Please ensure to remove pulsemixer.

**Comment by arek-e** [comment]
> Also can I learn which iso version you are using? Is it the latest one ?

Im using the latest one 1.04 did a fresh install yesterday.

**Comment by r0-zero** [comment]
@AlexanderEklund @xd003 Handling this issue currently. Try again in 50 minutes please, changing pulsemixer to pavucontrol.

**Comment by r0-zero** [comment]
Can you try it now? Dwm and system scripts have been updated, pacman -R pulsemixer if needed. Pavucontrol is the new application for managing sounds.

**Comment by arek-e** [comment]
Installed the new update and Pavucontrol is closing properly.
