### ISSUE TITLE
Can't compile dwm with custom keybindings

### ISSUE THREAD

**Issue by bpedrazaa** [FT-Labs/phyOS-iso#19]
I tried to compile dwm with my personal custom keybindings.
Follow all the instructions, copy the keys.h.default to keys.h, made all my changes and run "phyup dwm"

The following error appeared.
![image](https://user-images.githubusercontent.com/81981552/184364333-195120b5-1af0-47db-8255-efaabd936a0a.png)

I will love some help. Thanks in advance.
Btw, great work. I am using PhyOS as my main OS in my laptop <3

**Comment by r0-zero** [comment]
Hi, did you update the dots? keys.h.default is updated. Thanks for using!

```
phyup dots
OR
phyup dots --force
```

**Comment by bpedrazaa** [comment]
Hey, thanks for the fast response.
I runned the command and tried to recompile the new keys.h without any changes... And its working :)

Just one thing, is there a way to add rules?
Whenever I read the new keys.h.default  the rules array does not exist.
I want to set up some client windows to open in specific tags.

Again, thanks in advance.

**Comment by r0-zero** [comment]
Sure thing, no problem!

Please join our discord channel for updates, I post recent updates in discord. Rules are not static, they are now dynamic! You can set any rule you want by ``` pOS-pin ``` script. All options are there!

**Comment by bpedrazaa** [comment]
Thanks!

I'll join right away.
