### ISSUE TITLE
Text editor doesn't work properly the first time

### ISSUE THREAD

**Issue by arch-user-france1** [FT-Labs/phyOS-iso#2]
Starting the text-editor using the drop-down menu in the live system results in following:

![image](https://user-images.githubusercontent.com/72965843/180495953-0a75593b-4b61-41cc-940f-04ff4a240473.png)

However after pressing the "q" key it opens vim.
I just noticed that this also happens on an installed system.

**Comment by r0-zero** [comment]
Yes, it is a riced neovim and it needs to download its modules. Just ignore the errors, or open it with root. After the installation, it should automatically install its configuration & plugins.
