### ISSUE TITLE
lf bug

### ISSUE THREAD

**Issue by ddiaz2380** [FT-Labs/phyOS-iso#24]
When I use lf with the quick keys win + r the previews of images, videos and documents do not work, but if I run it from the terminal it does.

**Comment by r0-zero** [comment]
Could you please open pdwmc, in QT app:

Edit the command for Win+r, set it to: Terminal box checked, and the command is: /usr/bin/lfrun

**Comment by r0-zero** [comment]
By the way a sad news for this one, image preview has been out of support, and if no one takes care of ueberzug, it will be depracated soon unfortunately
