### ISSUE TITLE
start terminal error ssh-agent

### ISSUE THREAD

**Issue by ddiaz2380** [FT-Labs/phyOS-iso#25]
Starting ssh-agent ...
_start_agent:18: no existe el fichero o el directorio: /home/daniel/.config/ssh/environment-archlinux
chmod: no se puede acceder a '/home/daniel/.config/ssh/environment-archlinux': No existe el fichero o el directorio
_start_agent:.:20: no existe el fichero o el directorio: /home/daniel/.config/ssh/environment-archlinux

The ssh-agent is to be able to do the updates of the dotfiles? it is not clear to me...

**Comment by r0-zero** [comment]
This should be fixed with latest dotfiles, ssh agent is now optional

**Comment by ddiaz2380** [comment]
I have modified a lot of lf, .xprofile, zprofile and zsh
If I run phyup dots --force do I lose what I modified?
How do I solve it? by the way, will you make a debian iso? or how is it installed?
Thx!

**Comment by r0-zero** [comment]
Try ``` phyup dots ```, forcing it won't replace I think. 

Comment `eval ssh-agent` line in ~/.xprofile

Yeap, a debian iso, which will be actually ubuntu based is on the way. There won't be an installer for it, it is going to be installed from phyOS, which will download the source and handle everything in background. I am currently working on it, it is nearly done, for now, it will have 2 flavors (phyOS packages if preferred, otherwise classical gnome ubuntu) and the version is going to be kinetic kudu, 22.10.

**Comment by ddiaz2380** [comment]
Excellent, it's an iso like the one based on arch, but based on ubuntu... perfect.
Thank you very much for the work you dedicate to your distribution, Regards!

**Comment by r0-zero** [comment]
Thanks, I hope it will get much much better! Appreciate your kind comment!

**Comment by ddiaz2380** [comment]
Sorry for the last thing... in the settings when I change any option, be it font size or hotkey option. Closing it doesn't save the changes...

**Comment by r0-zero** [comment]
Hello, you need to build it with Ctrl+b or select build from top left menu

**Comment by ddiaz2380** [comment]
Great, it worked... thank you very much always for your time and
predisposition! I was these days with your distro and it works wonders,
very light, I got used to the fast keys and others. I just have to get more
used to nvim but it's a matter of time...
On the other hand, I still get the ssh-agent error when starting the
terminal, I disabled all the variables related to ssh-agent but nothing...
Going back to neovim, do you have documentation of nvim hotkeys, plugins
and other features?
Many thanks for everything!

**Comment by r0-zero** [comment]
Thanks!! Could you delete ssh plugin please, 
rm -rf ~/.config/zsh/zshcfg/OMZ/plugins/ssh*

Not yet unfortunately, i will do that after next release!

**Comment by ddiaz2380** [comment]
solved it by creating the ssh folder in ~/.config/ssh and giving it
permissions and then I ran ssh-agent and generated the pid correctly, it no
longer gives the error when starting the terminal.
