### ISSUE TITLE
In the Chinese environment, the terminal cannot display Chinese

### ISSUE THREAD

**Issue by lixiaya** [FT-Labs/phyOS-iso#28]
Hello, I am from China, I like your phyOS very much, but in the Chinese environment, the st terminal has been unable to display Chinese, even though I have downloaded Chinese fonts, it does not help. I try to install other desktop environments, such as cutefish. The terminal that comes with cutfish can display Chinese very well. Can you add support for Chinese in the next version?

**Comment by r0-zero** [comment]
Hello, could you please send screenshots?

Have you installed an IME that supports pinyin?

**Comment by lixiaya** [comment]
For example, when you enter yay -Syu, you will be prompted to enter the password, but only the account name can be displayed, as shown below
![118028225](https://user-images.githubusercontent.com/128228011/231327770-e7fab291-e50e-4d8c-afc9-3311cca7ea91.png)

The picture below is what should have happened
![2023-04-12_09-58](https://user-images.githubusercontent.com/128228011/231328052-1cdfdc0c-e9f0-458c-9581-809e02a3247e.png)

**Comment by lixiaya** [comment]
Hello, I think I know the problem, when I change the terminal to alacritty, Chinese shows up fine

**Comment by lixiaya** [comment]
Hello, I think I know the problem, when I change the terminal to alacritty, Chinese shows up fine

**Comment by r0-zero** [comment]
Have you added respected font to st?

**Comment by lixiaya** [comment]
> 您是否已将受人尊敬的字体添加到 st？

Hello, can you tell me where is the st configuration file?

**Comment by r0-zero** [comment]
It's not like pdwm for now, you need to edit the configuration file.

git clone https://github.com/FT-Labs/phyOS-st

cd into repo

Add your font into config.h in here

```
static char *fonts[] = {          "TerminessTTF Nerd Font:style=Medium:pixelsize=24",
						"Consolas Nerd Font:style=Regular:pixelsize=24",
						"JetBrains Mono:style=Regular:pixelsize=24",
                                                "MesloLGS NF:style=Regular:pixelsize=24"};
```

Then

``` make && sudo make install ```

**Comment by lixiaya** [comment]
> 暂时不像pdwm，需要编辑配置文件。
> 
> git 克隆https://github.com/FT-Labs/phyOS-st
> 
> cd 到 repo
> 
> 在此处将您的字体添加到 config.h
> 
> ```
> static char *fonts[] = {          "TerminessTTF Nerd Font:style=Medium:pixelsize=24",
> 						"Consolas Nerd Font:style=Regular:pixelsize=24",
> 						"JetBrains Mono:style=Regular:pixelsize=24",
>                                                 "MesloLGS NF:style=Regular:pixelsize=24"};
> ```
> 
> 然后
> 
> `make && sudo make install`

Thank you very much, it can be displayed normally

**Comment by r0-zero** [comment]
Anytime!
