### ISSUE TITLE
dwm crash on loading

### ISSUE THREAD

**Issue by iliketwertles** [FT-Labs/phyOS-iso#3]
i understand this is still in beta but id like to inform you that when i load the iso live from usb dwm crashes after everything loads in and kicks me back to the login manager

pc specs are listed:
i3 3220 
gtx 1650 super
8gb ddr3
usb was 32gb "Sandisk Ultra USB 3.0" (on bottom)

**Comment by r0-zero** [comment]
Can you try v1.0.1-beta, todays release

**Comment by r0-zero** [comment]
Don't try it, I have found the error. It is because of dynamic linked libraries, I will handle it today

**Comment by iliketwertles** [comment]
Yea sure thing, I'll just post anything I find on this issue

**Comment by rilysh** [comment]
Anyway, since you know...just to inform have the same issue on my end too

**Comment by r0-zero** [comment]
Hey guys, so everyone having getting kicked back to sddm has the same problem. Dwm uses some dynamically linked libraries, and it can depend from different cpu architectures. Creating monitor (createmon) and update geometry handling (updategeomhandling) throws out kernel errors. This is an issue with base dwm, I am trying to handle it currently. I will update this issue from here.

**Comment by rilysh** [comment]
Any updates on this? It's still an issue with latest version as well.

**Comment by wr4ck3r** [comment]
> Any updates on this? It's still an issue with latest version as well.

Yeah, there is, but it's not fixed yet
Check #bugs channel on [Discord server](https://discord.gg/UHdZ4Pzve3)

**Comment by r0-zero** [comment]
Fix in 1-2 days

**Comment by r0-zero** [comment]
https://github.com/FT-Labs/phyOS-iso/releases/tag/1.0.2-beta

Issue should be fixed, can you try the new release

**Comment by iliketwertles** [comment]
> https://github.com/FT-Labs/phyOS-iso/releases/tag/1.0.2-beta
> 
> Issue should be fixed, can you try the new release

Within the next few hours yes, it'll be on the same hardware

**Comment by iliketwertles** [comment]
on the same hardware no splash screen (known) but this time it was just sitting on a black screen, ctrl + alt + F1-F5 and so on didn't put me into any tty either. it seems the system was responsive at least a little bit being so caps lock light was turning on and off when the button was pressed. and it was the same usb just reflashed with latest iso.

something that might be worthy of noting is i have igpu set as default in bios (chromeos stuff but that's completely unrelated) but before in the old iso and every other distro still used dgpu as display not using igpu for anything, not even separate display. archcraft is what i main and it displays this. so i doubt that is anything to worry about but idk how/if this distro interprets stuff any different in that way, hence why im mentioning it here.

**Comment by arch-user-france1** [comment]
on the iso starting compiz will crash dwm

And oh my god calamares SUCKS I tried installing 10 times and it never worked.

**Comment by r0-zero** [comment]
Solved, closing issue
