### ISSUE TITLE
modify st

### ISSUE THREAD

**Issue by ddiaz2380** [FT-Labs/phyOS-iso#32]
Since I installed phyOS I have not had any problem and I am going for more than 1 year of use and everything is perfect. One question, how can I modify the source of st and add patches and so on?

**Comment by r0-zero** [comment]
Hello,

You can go directly for the source:

git clone git@github.com/FT-Labs/phyOS-st

Then add patches & compile after it. Delete ``` pacman -R phyOS-st ``` for it to not overwrite if new versions are released. I hope I will add a configuration menu for that as well

**Comment by ddiaz2380** [comment]
I saw that there was a combination of keys to change ST, Alt + sources, but
... it doesn't work or change it?
Always answering quickly and kindly, thank you very much!
