### ISSUE TITLE
st无法显示中文

### ISSUE THREAD

**Issue by hnsylzg** [FT-Labs/phyOS-iso#36]
![20231029104623](https://github.com/FT-Labs/phyOS-iso/assets/3788384/4aa1a21b-1e32-4baf-a9d4-a3f862f41605)
中文显示为空白

**Comment by r0-zero** [comment]
Hello could you write in latin please?

**Comment by hnsylzg** [comment]
Chinese text appears blank

**Comment by xmb9** [comment]
您好，如果写得不好，我很抱歉，我正在使用翻译。

问题是你需要下载并安装中文字体，然后将其添加到 st config.h 中。

请遵循以下说明：

`git clone https://github.com/FT-Labs/phyOS-st`

`cd phyOS-st`

Add your font into config.h in here

```
static char *fonts[] = {          "TerminessTTF Nerd Font:style=Medium:pixelsize=24",
						"Consolas Nerd Font:style=Regular:pixelsize=24",
						"JetBrains Mono:style=Regular:pixelsize=24",
                                                "MesloLGS NF:style=Regular:pixelsize=24"};
```
Then

`make && sudo make install`

**Comment by hnsylzg** [comment]
Thank you very much. The problem with st Chinese has been solved. I still have a question. I think the ui and text are too big. How can I make them smaller?

**Comment by r0-zero** [comment]
Thanks for @EnterTheVoid-x86 

Alt+shift+j, alt+shift+k to large/minimize font.

**Comment by hnsylzg** [comment]
Is there a way to shrink the entire interface? How to modify the code?

**Comment by xmb9** [comment]
> Thanks for @EnterTheVoid-x86
> 
> Alt+shift+j, alt+shift+k to large/minimize font.

No problem

**Comment by xmb9** [comment]
> Is there a way to shrink the entire interface? How to modify the code?

If you press Win+F5 you can change the scale of the screen and your resolution
