### ISSUE TITLE
Kernel error I think

### ISSUE THREAD

**Issue by Lufims** [FT-Labs/phyOS-iso#38]
First things first, I don't know much about arch Linux, I'm saying that because PhyOS is based on it.
Basically, I installed the distro, and I was having trouble with the Plymouth, so I tried to boot the "safe mode", and I was having the same issue, it was hanging on the "starting Terminate plymouth boot screen" or something, so I boot the terminal before it tried to star that service, and it booted correctly, but in the safe mode, so is used pacman to uninstall "Plymouth-git", but he safe mode uses another image, not the root image (I think is it how it says), so I tried to do the same thing on the normal boot, but when appear the login terminal, I type one key, and it doesn't work, I type it again, and It appears, I type the login, then press enter, appears to type the password, and for some reason, every key on my keyboard is the same thing as hitting enter, so I type the first letter of the password, it says that the login is incorrect, and it is, because a couldn't type the entire password, I tried the safe mode again to see if it was the same way, but It isn't, it's normal in that image, and now I can boot normally into the safe mode, but when o try the normally mode, it just stays in the spalsh screen indefinitely, and when I remove the splash screen, appears the login lines, that I can't type the correct password to boot the system.

And because of that, I need help, I literally don't have any idea of what is happening.

**Comment by r0-zero** [comment]
Could you please come to discord for troubleshooting?

**Comment by Lufims** [comment]
> Could you please come to discord for troubleshooting?

Ok
