### ISSUE TITLE
Terminal does not open and "broken" as a window name

### ISSUE THREAD

**Issue by inmaks** [FT-Labs/phyOS-iso#4]
On Lenovo Ideapad S340-15API, ISO released 5 hours ago is installed, it does not open st terminal, does not work from super+d and does not open pressing super+return
Also it writes "broken" as a window name with any window being active

**Comment by r0-zero** [comment]
Hi! So this is an issue with calamares actuallly, did you forget to set you locale when installing? You need to do this to regenerate your locale: 
``` sudo nvim /etc/locale.gen ```
In this file, please uncomment your language and comment all of the others:
like uncomment this:
``` en_US.UTF-8 ``` or whatever your language is.
After this ``` sudo locale-gen ``` 
Reboot and you are good to go!

**Comment by inmaks** [comment]
calamares added en_US AND en_AG somehow, removed everything unneeded and also changed en_AG to en_US in locale.conf. Thanks for the quick help.
