### ISSUE TITLE
Cannot run phyOS after installing.

### ISSUE THREAD

**Issue by YaNiMo001** [FT-Labs/phyOS-iso#7]
So I installed phyOS today via a bootable USB, everything went well. After the installation the OS told me to reboot my system. Like any human, I did. After rebooting and selecting phyOS in the boot menu nothing happened. I just got a black screen, not even a blinking dot, nothing.

This distro looks absolutely stunning, so I hope that I can try it out as soon as possible, probs to the developer.

**Comment by r0-zero** [comment]
Can you reach our from discord so we can troubleshoot?

**Comment by YaNiMo001** [comment]
I already did. You tried to help me, but it didn't work. You'll probably help me later on. I am Y.A.M.O. on Discord btw.

**Comment by r0-zero** [comment]
https://github.com/FT-Labs/phyOS-iso/releases/tag/1.0.2-beta

Issue should be fixed, can you try the new release?

**Comment by YaNiMo001** [comment]
Will try when I get home. Will report, thanks mate!

**Comment by r0-zero** [comment]
Desktop CPU intel with integrated graphics collide with nvidia KMS early loading. After the installation, remove i915 from /etc/mkinitcpio.conf, then ``` sudo plymouth-set-default-theme -R cyanide ``` reboot to fix this issue
