### ISSUE TITLE
stuck at blinking screen(1.0.2 iso)

### ISSUE THREAD

**Issue by mustafademiral** [FT-Labs/phyOS-iso#9]
I booted from USB and it's stuck at blinking screen. I've also tried NVIDIA boot option. 

My hardware: 
CPU: Intel i3-6098p
Motherboard: MSI H110M-PRO-VD
GPU: NVIDIA GTX1050Ti [GP107]

**Comment by mustafademiral** [comment]
Version 1.0.3 worked. I didn't notice new version. Thank you for your work.

**Comment by r0-zero** [comment]
All right, thanks for installing!
